openapi: 3.1.0
info:
  title: Trackster API
  version: "1.0.0"
  description: API documentation for Trackster, an API for tracking habits, streaks, and journals.
servers:
  - url: http://localhost:4000/api
paths:
  /{name}:
    get:
      tags:
        - streaks
      summary: Get a streak by name
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the streak.
          schema:
            type: string
      responses:
        '200':
          description: Successful response with streak data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreakResponse'
        '404':
          description: Streak not found.
    put:
      tags:
        - streaks
      summary: Create or update (increment) a streak
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the streak.
          schema:
            type: string
      responses:
        '200':
          description: Returns the streak data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreakResponse'
    delete:
      tags:
        - streaks
      summary: Delete a streak by name
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the streak.
          schema:
            type: string
      responses:
        '204':
          description: Streak deleted successfully.
        '404':
          description: Streak not found.
  /{name}/reset:
    patch:
      tags:
        - streaks
      summary: Reset a streak's counter to 0
      parameters:
        - name: name
          in: path
          required: true
          description: The name of the streak.
          schema:
            type: string
      responses:
        '200':
          description: Streak reset successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetStreakResponse'
        '404':
          description: Streak not found.
  /habits/today:
    get:
      tags:
        - habits
      summary: Get todays habits
      responses:
        '200':
          description: A list of habits for today.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitListResponse'
  /habits:
    get:
      tags:
        - habits
      summary: List all habits
      responses:
        '200':
          description: A list of all habits.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitListResponse'
    post:
      tags:
        - habits
      summary: Create a new habit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HabitInput'
      responses:
        '201':
          description: Habit created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitResponse'
  /habits/{id}:
    get:
      tags:
        - habits
      summary: Get a habit by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The habit ID.
          schema:
            type: integer
      responses:
        '200':
          description: Returns a habit.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitResponse'
        '404':
          description: Habit not found.
  /habits/{id}/complete:
    patch:
      tags:
        - habits
      summary: Mark a habit as complete
      parameters:
        - name: id
          in: path
          required: true
          description: The habit ID.
          schema:
            type: integer
      responses:
        '200':
          description: Habit updated after completion.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HabitResponse'
        '404':
          description: Habit not found.
  /journals/today:
    get:
      tags:
        - journals
      summary: Get todays journal entry
      responses:
        '200':
          description: Returns todays journal entry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalResponse'
    put:
      tags:
        - journals
      summary: Update todays journal entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JournalInput'
      responses:
        '200':
          description: Journal entry updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalResponse'
  /journals/{date}:
    get:
      tags:
        - journals
      summary: Get a journal entry by date
      parameters:
        - name: date
          in: path
          required: true
          description: The date of the journal entry (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Returns the journal entry for the specified date.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JournalResponse'
        '404':
          description: Journal entry not found.
components:
  schemas:
    StreakData:
      type: object
      properties:
        name:
          type: string
          description: Name of the streak.
        count:
          type: integer
          description: Current streak count.
        last_updated_at:
          type: string
          format: date-time
          description: Timestamp of the last update.
      required:
        - name
        - count
        - last_updated_at
    StreakResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/StreakData'
    ResetStreakResponse:
      type: object
      properties:
        message:
          type: string
          example: Streak reset successfully
        name:
          type: string
        count:
          type: integer
      required:
        - message
        - name
        - count
    HabitData:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        times_per_day:
          type: integer
        completed_count:
          type: integer
        last_completed:
          type: string
          format: date-time
          nullable: true
        inserted_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - times_per_day
        - completed_count
        - inserted_at
    HabitResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/HabitData'
    HabitListResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/HabitData'
    HabitInput:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        times_per_day:
          type: integer
      required:
        - name
        - times_per_day
    JournalData:
      type: object
      properties:
        id:
          type: integer
        entry_date:
          type: string
          format: date
        content:
          type: string
        inserted_at:
          type: string
          format: date-time
      required:
        - entry_date
    JournalResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/JournalData'
    JournalInput:
      type: object
      properties:
        content:
          type: string
      required:
        - content
